import { query, queryOne, withTransaction } from "./db.js";
import { migrateContractWorkflow } from "./contracts/workflow.js";
import { backfillHandoverShares } from "./contracts/handover.js";
import { ROLE_DUTIES, ROLE_REPLACEMENTS } from "./org/duties.js";
import { LEGACY_ACCOUNTS, demoPasswordFor, legacyPasswordFor } from "./org/demoCredentials.js";
import { organizationId } from "./org/rbac.js";
import { DEBT_STATUSES } from "./models/debt.js";
import { hashPassword, verifyPassword } from "./auth.js";

// Duties close the gap between a role and its raw permission list. They are the
// declared responsibilities that justify those permissions, which is what makes
// the access matrix auditable in both directions. `role_permissions` remains
// the single enforced source of truth the request middleware reads.
const dutySchema = `
CREATE TABLE IF NOT EXISTS duties (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  duty_key TEXT NOT NULL,
  label TEXT NOT NULL,
  description TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(role_id, duty_key)
);
CREATE TABLE IF NOT EXISTS duty_permissions (
  duty_id INTEGER NOT NULL REFERENCES duties(id) ON DELETE CASCADE,
  permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  PRIMARY KEY(duty_id, permission_id)
);
CREATE INDEX IF NOT EXISTS idx_duties_role ON duties(role_id);

-- Additive task-assignment workflow. Nothing existing is altered or dropped.
CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  assigned_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  assigned_to INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reviewer_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  department_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
  visibility TEXT NOT NULL DEFAULT 'own' CHECK (visibility IN ('own','department','organization')),
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('urgent','high','medium','low')),
  due_date TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'assigned' CHECK (status IN ('assigned','in_progress','submitted','under_review','approved','changes_requested','completed','cancelled')),
  linked_entity TEXT CHECK (linked_entity IN ('client','property','contract','payment','debt','project','report','document','appointment')),
  linked_record_id INTEGER,
  submitted_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  submitted_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  approved_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  completed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  completed_at TIMESTAMPTZ,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_tasks_org_status ON tasks(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned ON tasks(assigned_to, status);
CREATE INDEX IF NOT EXISTS idx_tasks_reviewer ON tasks(reviewer_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks(priority);
CREATE INDEX IF NOT EXISTS idx_tasks_link ON tasks(linked_entity, linked_record_id);
CREATE TABLE IF NOT EXISTS task_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  author_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_task_comments_task ON task_comments(task_id, created_at);
`;

// Explicit record sharing: a record can be shared with individual users or with a
// whole department without widening its ownership.
const sharingSchema = `
CREATE TABLE IF NOT EXISTS record_shares (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  entity TEXT NOT NULL,
  record_id INTEGER NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  department_id INTEGER REFERENCES departments(id) ON DELETE CASCADE,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (user_id IS NOT NULL OR department_id IS NOT NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_record_shares_unique ON record_shares (entity, record_id, COALESCE(user_id, 0), COALESCE(department_id, 0));
CREATE INDEX IF NOT EXISTS idx_record_shares_lookup ON record_shares (entity, record_id);
`;

// Records that participate in ownership scoping. Every one of them gains
// owner/creator/department/visibility columns; unassigned legacy rows stay in an
// office-wide pool until an administrator allocates them.
const scopedTables = ["projects", "clients", "contracts", "properties", "appointments", "documents", "debts", "payments", "reports", "leads", "follow_ups"];

const schema = `
CREATE TABLE IF NOT EXISTS organizations (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, display_name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'staff' CHECK (role IN ('admin','staff')), active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS departments (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(organization_id, name));
CREATE TABLE IF NOT EXISTS roles (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT, system_role BOOLEAN NOT NULL DEFAULT FALSE, rank INTEGER NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(organization_id, name));
CREATE TABLE IF NOT EXISTS permissions (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, permission_key TEXT NOT NULL UNIQUE, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_departments (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, department_id INTEGER NOT NULL REFERENCES departments(id) ON DELETE CASCADE, PRIMARY KEY(user_id, department_id));
CREATE TABLE IF NOT EXISTS user_roles (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE, PRIMARY KEY(user_id, role_id));
CREATE TABLE IF NOT EXISTS role_permissions (role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE, permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, PRIMARY KEY(role_id, permission_id));
CREATE TABLE IF NOT EXISTS projects (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','archived')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS clients (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL, name TEXT NOT NULL, email TEXT, phone TEXT, client_type TEXT NOT NULL DEFAULT 'buyer' CHECK(client_type IN ('buyer','seller','landlord','tenant')), status TEXT NOT NULL DEFAULT 'lead' CHECK(status IN ('lead','active','inactive')), notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS contracts (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE, client_id INTEGER REFERENCES clients(id) ON DELETE SET NULL, client_name TEXT NOT NULL, contract_type TEXT NOT NULL CHECK(contract_type IN ('new','terminal')), status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','closed','cancelled')), value NUMERIC(14,2) NOT NULL DEFAULT 0, original_price NUMERIC(14,2) NOT NULL DEFAULT 0, discount_pct NUMERIC(5,2) NOT NULL DEFAULT 0, discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0, start_date DATE, end_date DATE, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS debts (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, contract_id INTEGER NOT NULL REFERENCES contracts(id) ON DELETE CASCADE, client_name TEXT NOT NULL, amount NUMERIC(14,2) NOT NULL DEFAULT 0, due_date DATE, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','partial','paid','overdue')), notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS reminders (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, debt_id INTEGER NOT NULL REFERENCES debts(id) ON DELETE CASCADE, remind_at TIMESTAMPTZ NOT NULL, sent BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS properties (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL, name TEXT NOT NULL, property_type TEXT NOT NULL DEFAULT 'house' CHECK(property_type IN ('land','house','apartment','villa','commercial','penthouse')), status TEXT NOT NULL DEFAULT 'available' CHECK(status IN ('available','reserved','sold','leased')), price NUMERIC(14,2) NOT NULL DEFAULT 0, location TEXT NOT NULL, area NUMERIC(14,2) NOT NULL DEFAULT 0, bedrooms INTEGER NOT NULL DEFAULT 0, bathrooms INTEGER NOT NULL DEFAULT 0, description TEXT, featured BOOLEAN NOT NULL DEFAULT FALSE, public_listing BOOLEAN NOT NULL DEFAULT FALSE, public_listing_status TEXT NOT NULL DEFAULT 'private', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS appointments (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE, property_id INTEGER REFERENCES properties(id) ON DELETE SET NULL, project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL, title TEXT NOT NULL, appointment_type TEXT NOT NULL DEFAULT 'viewing' CHECK(appointment_type IN ('viewing','call','meeting','inspection')), starts_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ, status TEXT NOT NULL DEFAULT 'scheduled' CHECK(status IN ('scheduled','completed','cancelled')), notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS documents (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL, contract_id INTEGER REFERENCES contracts(id) ON DELETE SET NULL, client_id INTEGER REFERENCES clients(id) ON DELETE SET NULL, title TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'other', status TEXT NOT NULL DEFAULT 'pending', file_reference TEXT, notes TEXT, original_filename TEXT, stored_name TEXT, file_size BIGINT, mime_type TEXT, uploaded_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS payments (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, contract_id INTEGER NOT NULL REFERENCES contracts(id) ON DELETE CASCADE, debt_id INTEGER REFERENCES debts(id) ON DELETE SET NULL, client_name TEXT NOT NULL, amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK(amount >= 0), paid_at TIMESTAMPTZ NOT NULL, method TEXT NOT NULL DEFAULT 'cash', reference TEXT, notes TEXT, receipt_document_id INTEGER REFERENCES documents(id) ON DELETE SET NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS reports (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, title TEXT NOT NULL, report_type TEXT NOT NULL, source TEXT NOT NULL DEFAULT 'generated', project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL, description TEXT, filters_json JSONB, file_format TEXT, original_filename TEXT, stored_name TEXT, file_size BIGINT, mime_type TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS property_images (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE, original_filename TEXT, stored_name TEXT NOT NULL, file_size BIGINT, mime_type TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sessions (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, token_hash TEXT NOT NULL UNIQUE, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL, user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, action TEXT NOT NULL, module TEXT NOT NULL, record_id TEXT, details_json JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS leads (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, client_id INTEGER REFERENCES clients(id) ON DELETE SET NULL, name TEXT NOT NULL, email TEXT, phone TEXT, source TEXT, status TEXT NOT NULL DEFAULT 'new', assigned_to INTEGER REFERENCES users(id) ON DELETE SET NULL, notes TEXT, converted_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS follow_ups (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, lead_id INTEGER REFERENCES leads(id) ON DELETE CASCADE, client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE, assigned_to INTEGER REFERENCES users(id) ON DELETE SET NULL, due_at TIMESTAMPTZ NOT NULL, next_due_at TIMESTAMPTZ, follow_up_type TEXT NOT NULL DEFAULT 'call', status TEXT NOT NULL DEFAULT 'open', outcome TEXT, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS approvals (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, module TEXT NOT NULL, record_id INTEGER NOT NULL, requested_by INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT, approved_by INTEGER REFERENCES users(id) ON DELETE SET NULL, status TEXT NOT NULL DEFAULT 'pending', notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), decided_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS property_history (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE, user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, event TEXT NOT NULL, details JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS settings (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, setting_key TEXT NOT NULL, setting_value TEXT, UNIQUE(organization_id, setting_key));
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id); CREATE INDEX IF NOT EXISTS idx_contracts_project ON contracts(project_id); CREATE INDEX IF NOT EXISTS idx_debts_contract ON debts(contract_id); CREATE INDEX IF NOT EXISTS idx_debts_due ON debts(due_date); CREATE INDEX IF NOT EXISTS idx_properties_project ON properties(project_id); CREATE INDEX IF NOT EXISTS idx_clients_project ON clients(project_id); CREATE INDEX IF NOT EXISTS idx_documents_project ON documents(project_id); CREATE INDEX IF NOT EXISTS idx_payments_contract ON payments(contract_id); CREATE INDEX IF NOT EXISTS idx_reports_created ON reports(created_at);
`;

// Business modules that can be granted independently of each other. A role needs
// `access_<module>` before it can touch that module at all; the generic
// view/create/edit/delete permissions then decide which actions are allowed.
export const MODULES = ["projects", "properties", "clients", "leads", "contracts", "documents", "appointments", "debts", "payments", "reminders", "reports", "follow_ups"];
const MODULE_LABELS = { projects: "Projects", properties: "Properties", clients: "Clients", leads: "Leads", contracts: "Contracts", documents: "Documents", appointments: "Appointments", debts: "Debts", payments: "Payments", reminders: "Reminders", reports: "Reports", follow_ups: "Follow-ups" };
const permissions = [
  ["view", "View records"],
  ["create", "Create records"],
  ["edit", "Edit records"],
  ["delete", "Delete records"],
  ["approve", "Approve records"],
  ["export", "Export reports"],
  ["manage_users", "Manage users"],
  ["manage_roles", "Manage roles"],
  ["manage_permissions", "Manage permissions"],
  ["manage_settings", "Manage organization settings"],
  ["view_financial", "View financial data"],
  ["view_reports", "View reports"],
  // Read-only access to the system/security audit trail. Granted to ICT for
  // security investigation, but deliberately carries no business-module access
  // and cannot write, decide or administer anything.
  ["view_audit", "View system and security audit log"],
  // Contract lifecycle. Department != role != permission: these keys are what
  // actually decide who may move a contract through the MKUYU workflow, and they
  // are granted independently of the generic view/create/edit/delete keys.
  ["submit_contract", "Submit a contract to Legal"],
  ["review_legal", "Review contracts (Legal)"],
  ["request_changes", "Request changes to a contract"],
  ["approve_legal", "Approve a contract from the legal perspective"],
  ["validate_finance", "Validate contract financial terms"],
  ["approve_management", "Approve a contract on behalf of management"],
  // Task assignment workflow (additive). The minimum pair the existing
  // permission list lacks: authority to hand work to somebody, and authority to
  // review/approve the work handed back. Neither grants any business-module
  // access, and both are enforced server-side against department/organization
  // scope, never by hiding a button.
  ["assign_tasks", "Assign work to staff within authorized scope"],
  ["review_tasks", "Review and approve submitted work"],
  // Contract templates decide the wording of every contract the company issues,
  // so uploading, replacing and choosing the default is a named authority of
  // its own (MD, ICT administration, the sales officers, Legal Officer), not
  // something every document user can do.
  ["upload_contract_templates", "Upload and manage contract templates"],
  // Read-only sight of a module: the holder may look, never change anything.
  ["view_projects", "See projects (read only)"],
  ["view_properties", "See properties (read only)"],
  ["view_appointments", "See appointments (read only)"],
  ...MODULES.map((module) => [`access_${module}`, `Access ${MODULE_LABELS[module] || module}`]),
];
const businessAccess = MODULES.map((module) => `access_${module}`);
const administrationAccess = [...businessAccess, "manage_users", "manage_roles", "manage_permissions", "manage_settings"];
// System administration only. ICT owns the system, never the business, so this
// list deliberately omits every `access_*` key, `approve`, `view_financial`,
// `export` and the whole contract lifecycle. `view_audit` is read-only security
// visibility: without a report module there is nothing for `export` to export.
const systemAccess = ["manage_users", "manage_roles", "manage_permissions", "manage_settings", "view", "view_reports", "view_audit"];
const contractLifecycle = ["submit_contract", "review_legal", "request_changes", "approve_legal", "validate_finance", "approve_management"];
// Task workflow authority. `assign_tasks` and `review_tasks` are held only by
// roles that already carry organizational authority: the break-glass system
// administrator, the Managing Director, and the department managers who
// supervise a desk. Every other role receives and works, never assigns.
const taskWorkflow = ["assign_tasks", "review_tasks"];


// name, description, rank, data scope, permissions
//
// These permissions are derived from the duty catalogue in org/duties.js: the
// union of a role's duties must equal the permission set declared here, and
// the access-matrix test asserts that in both directions.
// Contract lifecycle keys are therefore held only by their owning department:
//   submit_contract    -> SALES, MARKETING & OPERATIONS
//   review_legal / approve_legal / request_changes -> LEGAL
//   validate_finance   -> FINANCE & ACCOUNTS
//   approve_management -> MANAGEMENT
export const defaultRoles = [
  ["System Administrator", "Full organization administration and documented break-glass business access", 100, "organization", [...administrationAccess, "view", "create", "edit", "delete", "approve", "export", "view_financial", "view_reports", "view_audit", ...contractLifecycle, ...taskWorkflow, "upload_contract_templates"]],

  // MANAGEMENT. Approves where the business rules require it. Deliberately has
  // no system administration and no authority to review or rewrite legal terms.
  ["Managing Director", "Organization-wide business authority and management approval. No system administration.", 80, "organization", ["access_projects", "access_properties", "access_clients", "access_leads", "access_contracts", "access_documents", "access_appointments", "access_follow_ups", "access_debts", "access_payments", "access_reminders", "access_reports", "view", "create", "edit", "delete", "approve", "export", "view_financial", "view_reports", "approve_management", "request_changes", ...taskWorkflow, "upload_contract_templates"]],

  // LEGAL. Owns the contract lifecycle and the final contract record.
  ["Legal Manager", "Owns the contract record and supervises the legal desk", 45, "department", ["access_contracts", "access_documents", "access_clients", "view_projects", "view_properties", "view_appointments", "access_reports", "view", "create", "edit", "delete", "approve", "export", "view_reports", "review_legal", "request_changes", "approve_legal", "upload_contract_templates", ...taskWorkflow]],
  ["Legal Officer", "Prepares, reviews and controls contract records", 35, "department", ["access_contracts", "access_documents", "access_clients", "view_projects", "view_properties", "view_appointments", "access_reports", "view", "create", "edit", "delete", "approve", "view_reports", "review_legal", "request_changes", "approve_legal", "upload_contract_templates"]],

  // ICT & ADMINISTRATION. Controls the system, never the business.
  ["ICTO", "Controls accounts, roles, permissions, settings, security and audit. No business authority.", 35, "organization", [...systemAccess, "upload_contract_templates"]],
  ["Administration & IT Support Officer", "Staff support, staff records and technical support. No business authority.", 20, "department", ["manage_users", "view", "view_reports", "export"]],

  // FINANCE & ACCOUNTS. Owns money and validates the financial terms.
  ["Finance Manager", "Runs finance operations and validates contract financial terms", 30, "department", ["access_debts", "access_payments", "access_reminders", "access_reports", "access_contracts", "access_clients", "access_follow_ups", "view_projects", "view_properties", "view_appointments", "view", "create", "edit", "delete", "approve", "export", "view_financial", "view_reports", "validate_finance", "request_changes", ...taskWorkflow]],
  ["Finance Officer", "Payments, installments, receipts and financial term validation", 15, "own", ["access_debts", "access_payments", "access_reminders", "access_reports", "access_contracts", "access_clients", "view_projects", "view_properties", "view_appointments", "view", "create", "edit", "view_financial", "view_reports", "validate_finance", "request_changes"]],

  // SALES, MARKETING & OPERATIONS. Initiates deals, never approves them.
  ["Department Manager", "Department-wide operational management and team supervision", 40, "department", ["access_projects", "access_properties", "access_clients", "access_leads", "access_appointments", "access_documents", "access_follow_ups", "access_reports", "access_contracts", "view", "create", "edit", "delete", "approve", "export", "view_reports", "submit_contract", "request_changes", ...taskWorkflow]],
  ["Sales, Marketing & Operations Officer", "Initiates deals and supplies customer, property and project detail", 20, "own", ["access_leads", "access_clients", "access_properties", "access_projects", "access_contracts", "access_appointments", "access_documents", "access_follow_ups", "access_reports", "view", "create", "edit", "view_reports", "submit_contract", "request_changes", "upload_contract_templates"]],
  ["Sales Officer", "Leads, clients, viewings and deal initiation", 15, "own", ["access_leads", "access_clients", "access_properties", "access_projects", "access_contracts", "access_appointments", "access_follow_ups", "access_reports", "view", "create", "edit", "view_reports", "submit_contract", "upload_contract_templates"]],
  ["Marketing Officer", "Campaign leads, listings and marketing documents", 15, "own", ["access_leads", "access_clients", "access_properties", "access_projects", "access_documents", "access_appointments", "access_reports", "view", "create", "edit", "view_reports"]],
  ["Property Officer", "Estate inventory, listings and viewings", 15, "own", ["access_properties", "access_projects", "access_clients", "access_appointments", "access_documents", "view", "create", "edit"]],

  // CUSTOMER SERVICE. Communicates and follows up; owns no contract content.
  ["Customer Service Manager", "Runs the customer service desk and its follow-up discipline", 32, "department", ["access_clients", "access_appointments", "access_leads", "access_follow_ups", "view_properties", "access_reports", "view", "create", "edit", "delete", "approve", "export", "view_reports", ...taskWorkflow]],
  ["Customer Service Officer", "Customer communication, viewings and follow-up; escalates contract questions to Legal", 15, "own", ["access_clients", "access_appointments", "access_leads", "access_follow_ups", "view_properties", "access_reports", "view", "create", "edit", "view_reports"]],

  // DIASPORA DESK. Serves customers who live abroad (Miliki Ardhi Diaspora):
  // sign-ups, their requests, document checks and follow-up. Department scope on
  // purpose: the desk works as ONE shared queue, so every desk member sees every
  // diaspora customer and several can work at the same time.
  ["Diaspora Desk Manager", "Runs the diaspora desk: its shared customer queue, document checks, diaspora contracts and the team's work", 32, "department", ["submit_contract", "access_contracts", "request_changes", "access_clients", "access_leads", "access_appointments", "access_follow_ups", "access_documents", "view_properties", "view_projects", "access_reports", "view", "create", "edit", "delete", "approve", "export", "view_reports", ...taskWorkflow]],
  ["Diaspora Desk Officer", "Serves diaspora customers from the shared desk queue: requests, follow-up, the first document check and preparing their contracts", 15, "department", ["submit_contract", "access_contracts", "request_changes", "access_clients", "access_leads", "access_appointments", "access_follow_ups", "access_documents", "view_properties", "view_projects", "access_reports", "view", "create", "edit", "view_reports"]],

  ["Staff Member", "Basic operational access to own records", 10, "own", ["access_clients", "access_appointments", "view", "create", "edit"]],

  // Small-office structure (under 10 staff): one person covers each desk, so
  // these roles carry the whole department's work without a manager above
  // them. Only the Managing Director assigns work. Added alongside the older
  // roles above; those are retired once this structure has been reviewed.
  // The MD, Legal Officer and Customer Service Officer keep their existing roles.
  ["Sales & Marketing Officer", "Leads, clients, properties, listings and viewings for the whole sales desk. Creates and submits contracts; never approves them.", 25, "department", ["access_leads", "access_clients", "access_properties", "access_projects", "access_contracts", "access_appointments", "access_documents", "access_follow_ups", "access_reports", "view", "create", "edit", "delete", "export", "view_reports", "submit_contract", "request_changes", "upload_contract_templates", ...taskWorkflow]],
  // Organization scope on purpose: installments belong to the SALES department
  // that made the deal, so a department-scoped accountant would not see them.
  ["Accountant", "Deposits, installments, payments and overdue follow-up for the whole finance desk. Checks the money on every contract.", 25, "organization", ["access_debts", "access_payments", "access_reminders", "access_reports", "access_contracts", "access_clients", "access_follow_ups", "view_projects", "view_properties", "view_appointments", "view", "create", "edit", "delete", "export", "view_financial", "view_reports", "validate_finance", "request_changes"]],
  ["ICT Officer", "Staff accounts, settings, security, backups and technical support. No business authority.", 35, "organization", [...systemAccess, "upload_contract_templates"]],
];


// The MKUYU organization. Renaming in place (see `departmentRenames`) keeps every
// user_departments row and every record's department_id intact; merging folds
// "Projects & Property" into the operations department rather than orphaning it.
export const departments = ["MANAGEMENT", "FINANCE & ACCOUNTS", "SALES, MARKETING & OPERATIONS", "ICT & ADMINISTRATION", "LEGAL", "CUSTOMER SERVICE", "DIASPORA DESK"];
const departmentRenames = {
  Management: "MANAGEMENT",
  "Finance & Administration": "FINANCE & ACCOUNTS",
  "Sales & Marketing": "SALES, MARKETING & OPERATIONS",
  "Projects & Property": "SALES, MARKETING & OPERATIONS",
  "IT / System Administration": "ICT & ADMINISTRATION",
  "Contracts / Legal": "LEGAL",
  "Customer Service & Collections": "CUSTOMER SERVICE",
};
// Roles whose name changed: existing user_roles rows are repointed so nobody
// silently loses their access after an upgrade.
const roleRenames = { "Contracts & Legal Officer": "Legal Officer" };

/**
 * Public website listing.
 *
 * The Sales Officer decides, on each property, whether it is
 * offered to Rent, to Buy or both, its rent price and period, a short card
 * summary, its features, and whether it shows on the public website. There is
 * no management approval step: ticking "show on the website" publishes it.
 *
 * `properties.price` stays the sale price. `public_listing` already existed and
 * becomes the publish switch; `public_listing_status` is kept in step with it
 * ('approved' when published) for the older /org/public-listings reader.
 *
 * Additive and idempotent: new columns default to "not offered, not
 * published", so nothing reaches the public site until someone publishes it.
 */
// Sessions carry how long they may live and when they were last used (MK-06).
// Every contract says which deal it is: Buy, Rent or Sell. Required for new
// contracts (the API refuses a contract without it); older rows stay NULL
// and show as "not recorded" until someone edits them.
// Payment approval (Finance). A newly recorded payment is "pending" until an
// authorised Finance user approves it. Payments recorded before approval
// existed are treated as approved, so nothing already in the books changes.
// A Sell submission from the website carries the seller's property details.
async function migrateSellLeads() {
  await query("ALTER TABLE leads ADD COLUMN IF NOT EXISTS sell_details JSONB");
}

async function migratePaymentApproval() {
  const had = await queryOne("SELECT 1 AS ok FROM information_schema.columns WHERE table_name='payments' AND column_name='status'");
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS status TEXT");
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS approved_by INTEGER REFERENCES users(id) ON DELETE SET NULL");
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ");
  if (!had) await query("UPDATE payments SET status='approved' WHERE status IS NULL");
  await query("UPDATE payments SET status='pending' WHERE status IS NULL");
  await query("ALTER TABLE payments ALTER COLUMN status SET DEFAULT 'pending'");
  await query("ALTER TABLE payments ALTER COLUMN status SET NOT NULL");
  await query("ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_status_check");
  await query("ALTER TABLE payments ADD CONSTRAINT payments_status_check CHECK (status IN ('pending','approved','reversed'))");
  // Payment safety (phase 1): the evidence behind a payment, and a reversal that
  // keeps the record instead of deleting it.
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS evidence_text TEXT");
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS reversed_by INTEGER REFERENCES users(id) ON DELETE SET NULL");
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMPTZ");
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS reversal_reason TEXT");
  // Set when the only Finance person approved a payment they recorded themselves
  // (single-Finance mode); kept on the record so the MD can review those.
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS self_approved BOOLEAN NOT NULL DEFAULT FALSE");
  // How an approved payment is spread over a contract's installments: oldest
  // unpaid first, any surplus onto the next. One payment may settle several
  // installments; an installment's paid amount is the sum of its allocations.
  await query(`CREATE TABLE IF NOT EXISTS payment_allocations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER REFERENCES organizations(id) ON DELETE CASCADE,
    payment_id INTEGER NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    debt_id INTEGER NOT NULL REFERENCES debts(id) ON DELETE CASCADE,
    amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await query("CREATE INDEX IF NOT EXISTS idx_payment_allocations_debt ON payment_allocations(debt_id)");
  await query("CREATE INDEX IF NOT EXISTS idx_payment_allocations_payment ON payment_allocations(payment_id)");
  // MKUYU's own receipt number, issued when a payment is approved.
  await query("CREATE SEQUENCE IF NOT EXISTS payment_receipt_seq");
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS receipt_number TEXT");
  await query("CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_receipt_number ON payments(receipt_number) WHERE receipt_number IS NOT NULL");
  await query(`UPDATE payments SET receipt_number = 'RCT-' || to_char(COALESCE(approved_at, created_at), 'YYYY') || '-' || lpad(nextval('payment_receipt_seq')::text, 6, '0')
     WHERE status IN ('approved','reversed') AND receipt_number IS NULL`);
  // Money paid back to a customer (a lease's security deposit, a cancelled deal).
  // Recorded with its reference and proof, confirmed like a payment.
  await query(`CREATE TABLE IF NOT EXISTS refunds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER REFERENCES organizations(id) ON DELETE CASCADE,
    contract_id INTEGER NOT NULL REFERENCES contracts(id) ON DELETE RESTRICT,
    amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    paid_at DATE NOT NULL,
    method TEXT NOT NULL DEFAULT 'bank',
    reference TEXT NOT NULL,
    reason TEXT NOT NULL,
    evidence_text TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved')),
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    approved_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    approved_at TIMESTAMPTZ,
    self_approved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await query("CREATE INDEX IF NOT EXISTS idx_refunds_contract ON refunds(contract_id)");
  // Payments approved before allocations existed keep exactly what they paid:
  // their whole amount on the installment they were recorded against.
  await query(`INSERT INTO payment_allocations (organization_id, payment_id, debt_id, amount)
    SELECT p.organization_id, p.id, p.debt_id, p.amount FROM payments p
     WHERE p.status = 'approved' AND p.debt_id IS NOT NULL AND p.amount > 0
       AND NOT EXISTS (SELECT 1 FROM payment_allocations pa WHERE pa.payment_id = p.id)`);
  // One transaction reference may back only one live payment. The index is the
  // database's own guarantee; the API checks first so it can explain the clash.
  // Older data may already hold duplicates: then the index is left out (and the
  // API check still protects every new payment) rather than failing startup.
  const duplicates = await queryOne(`SELECT COUNT(*)::int AS n FROM (
      SELECT 1 FROM payments WHERE reference IS NOT NULL AND btrim(reference) <> '' AND status <> 'reversed'
      GROUP BY organization_id, upper(regexp_replace(reference, '\\s', '', 'g')) HAVING COUNT(*) > 1) d`);
  if (!duplicates?.n) {
    await query(`CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_reference_unique
      ON payments (organization_id, upper(regexp_replace(reference, '\\s', '', 'g')))
      WHERE reference IS NOT NULL AND btrim(reference) <> '' AND status <> 'reversed'`);
  } else {
    console.warn(`payments: ${duplicates.n} transaction reference(s) are used more than once; the unique index was not created. Review them in Payments.`);
  }
}

async function migrateContractDealType() {
  // Who approved a request becoming a client (Sales or the MD).
  await query("ALTER TABLE leads ADD COLUMN IF NOT EXISTS converted_by INTEGER REFERENCES users(id) ON DELETE SET NULL");
  // A Rent contract is about a property only: it has no project.
  await query("ALTER TABLE contracts ALTER COLUMN project_id DROP NOT NULL");
  // A property's state per category: sale (available/reserved/sold) and rent
  // (available/reserved/rented). Backfilled once from the single status.
  await query("ALTER TABLE properties ADD COLUMN IF NOT EXISTS sale_status TEXT");
  await query("ALTER TABLE properties ADD COLUMN IF NOT EXISTS rent_status TEXT");
  await query(`UPDATE properties SET sale_status = CASE status WHEN 'sold' THEN 'sold' WHEN 'reserved' THEN 'reserved' ELSE 'available' END WHERE sale_status IS NULL`);
  await query(`UPDATE properties SET rent_status = CASE status WHEN 'leased' THEN 'rented' WHEN 'reserved' THEN 'reserved' ELSE 'available' END WHERE rent_status IS NULL`);
  await query("ALTER TABLE properties ALTER COLUMN sale_status SET DEFAULT 'available'");
  await query("ALTER TABLE properties ALTER COLUMN rent_status SET DEFAULT 'available'");
  await query("ALTER TABLE properties DROP CONSTRAINT IF EXISTS properties_sale_status_check");
  await query("ALTER TABLE properties ADD CONSTRAINT properties_sale_status_check CHECK (sale_status IN ('available','reserved','sold'))");
  await query("ALTER TABLE properties DROP CONSTRAINT IF EXISTS properties_rent_status_check");
  await query("ALTER TABLE properties ADD CONSTRAINT properties_rent_status_check CHECK (rent_status IN ('available','reserved','rented'))");
  await query("ALTER TABLE contracts ADD COLUMN IF NOT EXISTS deal_type TEXT");
  await query("ALTER TABLE contracts DROP CONSTRAINT IF EXISTS contracts_deal_type_check");
  await query("ALTER TABLE contracts ADD CONSTRAINT contracts_deal_type_check CHECK (deal_type IS NULL OR deal_type IN ('buy','rent','sell'))");
  await query("CREATE INDEX IF NOT EXISTS idx_contracts_deal_type ON contracts(deal_type)");
  // The title deed (or certificate of occupancy) the agreement is about.
  await query("ALTER TABLE contracts ADD COLUMN IF NOT EXISTS title_deed_number TEXT");
  // A contract template may be written for one kind of deal (Buy, Rent or
  // Sell) or, when NULL, be the letterhead every contract is placed on.
  await query("ALTER TABLE documents ADD COLUMN IF NOT EXISTS template_deal_type TEXT");
  await query("ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_template_deal_type_check");
  await query("ALTER TABLE documents ADD CONSTRAINT documents_template_deal_type_check CHECK (template_deal_type IS NULL OR template_deal_type IN ('buy','rent','sell'))");
}

async function migrateSessionSecurity() {
  await query("ALTER TABLE sessions ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()");
  await query("ALTER TABLE sessions ADD COLUMN IF NOT EXISTS remember BOOLEAN NOT NULL DEFAULT TRUE");
  await query("CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at)");
  // Expired sessions are removed rather than accumulating.
  await query("DELETE FROM sessions WHERE expires_at <= NOW()");
}

async function migratePublicListing() {
  for (const column of [
    "offer_rent BOOLEAN NOT NULL DEFAULT FALSE",
    "offer_buy BOOLEAN NOT NULL DEFAULT FALSE",
    "rent_price NUMERIC(14,2)",
    "rent_period TEXT NOT NULL DEFAULT 'month'",
    "summary TEXT",
    "features TEXT",
  ]) await query(`ALTER TABLE properties ADD COLUMN IF NOT EXISTS ${column}`);
  await query("CREATE INDEX IF NOT EXISTS idx_properties_public ON properties(public_listing) WHERE public_listing");
  // A project is only a category that properties belong to: no photos, no
  // price, no publishing of its own. The website derives projects from the
  // published properties in them.

  // Website requests (Buy / Rent) and enquiries arrive as Leads for Sales.
  for (const column of [
    "budget NUMERIC(14,2)",
    "service TEXT",
    "property_id INTEGER REFERENCES properties(id) ON DELETE SET NULL",
    "preferred_contact TEXT",
  ]) await query(`ALTER TABLE leads ADD COLUMN IF NOT EXISTS ${column}`);
  // A Buy/Rent request is followed through the Customer Service task it was
  // handed to (Requests view): the task's progress is the request's stage.
  await query("ALTER TABLE leads ADD COLUMN IF NOT EXISTS task_id INTEGER REFERENCES tasks(id) ON DELETE SET NULL");
  await query("ALTER TABLE leads ADD COLUMN IF NOT EXISTS handed_off_at TIMESTAMPTZ");
  // What Customer Service found when they contacted the customer, reported
  // back to Sales with the task: appointment / interested / declined /
  // unreachable. An appointment becomes a real Appointment (and the customer a
  // client) only when Sales approves the report.
  for (const column of [
    "outcome TEXT",
    "outcome_note TEXT",
    "outcome_at TIMESTAMPTZ",
    "outcome_by INTEGER REFERENCES users(id) ON DELETE SET NULL",
    "appointment_at TIMESTAMPTZ",
    "appointment_type TEXT",
    "appointment_id INTEGER REFERENCES appointments(id) ON DELETE SET NULL",
  ]) await query(`ALTER TABLE leads ADD COLUMN IF NOT EXISTS ${column}`);
}

/**
 * Widens the `debts.status` CHECK to include `partial`.
 *
 * An installment that has received some but not all of its money is a real state
 * that Finance needs to see, so the column's vocabulary has to admit it. This is
 * the only structural change the partial-status work requires: no column is
 * added, dropped or retyped, and no existing row is rewritten.
 *
 * Idempotent, and safe on a fresh database (the drop is IF EXISTS). The
 * constraint is dropped before being re-added because Postgres has no
 * "replace constraint" and the original is auto-named.
 *
 * The advisory lock serialises the drop-then-add pair across processes: two
 * servers booting at the same time would otherwise both drop, and the second
 * would fail with "constraint already exists".
 */
async function migrateInstallmentStatus() {
  await withTransaction(async (client) => {
    await client.query("SELECT pg_advisory_xact_lock(88102)");
    await client.query("ALTER TABLE debts DROP CONSTRAINT IF EXISTS debts_status_check");
    await client.query(`ALTER TABLE debts ADD CONSTRAINT debts_status_check CHECK (status IN (${DEBT_STATUSES.map((status) => `'${status}'`).join(",")}))`);
  });
}


/**
 * Phase 2.1: contract pricing columns.
 *
 * `contracts.value` stays the single authoritative contract amount and is
 * redefined as the FINAL PRICE, so every existing consumer (payment schedule,
 * reports, exports, dashboards) keeps reading one number and there is no second
 * definition of "what this contract is worth" that could drift.
 *
 * Only the two inputs and the calculated discount are stored alongside it. A
 * separate `final_price` column is deliberately NOT added: it would duplicate
 * `value` and the two could disagree. The API exposes `final_price` as an alias
 * of `value` so callers see the pricing breakdown without a redundant column.
 *
 * Backfill is safe and conservative: a contract that predates this feature has no
 * historical discount record, so it is treated as list price with no discount and
 * its existing financial value is preserved exactly. No historical discount is
 * ever invented.
 */
async function migrateContractPricing() {
  await query("ALTER TABLE contracts ADD COLUMN IF NOT EXISTS original_price NUMERIC(14,2)");
  await query("ALTER TABLE contracts ADD COLUMN IF NOT EXISTS discount_pct NUMERIC(5,2) NOT NULL DEFAULT 0");
  await query("ALTER TABLE contracts ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0");
  // Every existing contract becomes "list price, no discount" exactly once. The
  // `discount_pct IS NULL` guard is a no-op on re-runs because the column is NOT NULL.
  await query(`
    UPDATE contracts
       SET original_price = value,
           discount_pct = 0,
           discount_amount = 0
     WHERE original_price IS NULL
  `);
  // The calculated discount is derived, so it is kept consistent with the inputs.
  await query(`
    UPDATE contracts
       SET discount_amount = ROUND(original_price * discount_pct / 100, 2)
     WHERE original_price IS NOT NULL
  `);
  // `value` is the final price by definition; recompute it so the invariant holds
  // for every row, existing and new.
  await query(`
    UPDATE contracts
       SET value = original_price - discount_amount
     WHERE original_price IS NOT NULL AND discount_amount IS NOT NULL
  `);
  await query("ALTER TABLE contracts ALTER COLUMN original_price SET NOT NULL");
  await query("ALTER TABLE contracts ALTER COLUMN original_price SET DEFAULT 0");
}

export async function runMigrations({ seedDemo = process.env.NODE_ENV !== "production" && process.env.MKUYU_IS_TEST_DATABASE === "1" } = {}) {
  await query(schema);
  await query("ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_photo_stored_name TEXT");
  await query("ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_photo_mime_type TEXT");
  await query("ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_photo_updated_at TIMESTAMPTZ");
  await query(sharingSchema);
  await query(dutySchema);
  await query("ALTER TABLE roles ADD COLUMN IF NOT EXISTS rank INTEGER NOT NULL DEFAULT 0");
  await query("ALTER TABLE roles ADD COLUMN IF NOT EXISTS scope TEXT NOT NULL DEFAULT 'own'");
  await migrateContractWorkflow();
  await migrateInstallmentStatus();
  await migrateContractPricing();
  await migratePublicListing();
  await migrateSessionSecurity();
  await migrateContractDealType();
  await migratePaymentApproval();
  // Administrator-approved password reset: while the window is open the staff
  // member sets a new password from "Forgot password?" on the sign-in screen.
  await query("ALTER TABLE users ADD COLUMN IF NOT EXISTS password_reset_expires_at TIMESTAMPTZ");
  // The signed contract made or signed outside the system (a scan or PDF). It
  // takes the place of the generated agreement as the contract's official copy;
  // the generated one and every earlier signed copy stay in Documents.
  await query("ALTER TABLE contracts ADD COLUMN IF NOT EXISTS signed_document_id INTEGER REFERENCES documents(id) ON DELETE SET NULL");
  await query("ALTER TABLE contracts ADD COLUMN IF NOT EXISTS signed_uploaded_by INTEGER REFERENCES users(id) ON DELETE SET NULL");
  await query("ALTER TABLE contracts ADD COLUMN IF NOT EXISTS signed_uploaded_at TIMESTAMPTZ");
  await query("ALTER TABLE contracts ADD COLUMN IF NOT EXISTS signed_by_names TEXT");
  // Who the bank or mobile-money message says paid: the next payment from the
  // same phone or name is suggested for the same contract.
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS payer_name TEXT");
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS payer_phone TEXT");
  // Customer e-mails (receipts and payment reminders) and their delivery log.
  await query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS receipt_emailed_at TIMESTAMPTZ");
  await query(`CREATE TABLE IF NOT EXISTS email_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL, recipient TEXT, subject TEXT,
    payment_id INTEGER REFERENCES payments(id) ON DELETE SET NULL,
    debt_id INTEGER REFERENCES debts(id) ON DELETE SET NULL,
    contract_id INTEGER REFERENCES contracts(id) ON DELETE SET NULL,
    status TEXT NOT NULL, error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await query("CREATE INDEX IF NOT EXISTS email_log_debt_idx ON email_log (kind, debt_id)");
  await query("ALTER TABLE users ADD COLUMN IF NOT EXISTS password_reset_by INTEGER REFERENCES users(id) ON DELETE SET NULL");
  // Buildings: a project can be an estate (separate homes or plots) or one
  // building with floors. Each unit records its floor and the unit number the
  // staff gives it; a number is used once per project. A unit is offered to
  // rent, to buy, or both, like any property.
  await query("ALTER TABLE projects ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'estate'");
  await query("ALTER TABLE projects DROP CONSTRAINT IF EXISTS projects_kind_check");
  await query("ALTER TABLE projects ADD CONSTRAINT projects_kind_check CHECK (kind IN ('estate','building'))");
  await query("ALTER TABLE projects ADD COLUMN IF NOT EXISTS location TEXT");
  await query("ALTER TABLE properties ADD COLUMN IF NOT EXISTS floor INTEGER");
  await query("ALTER TABLE properties ADD COLUMN IF NOT EXISTS unit_number TEXT");
  await query("CREATE UNIQUE INDEX IF NOT EXISTS idx_properties_project_unit ON properties (project_id, lower(unit_number)) WHERE project_id IS NOT NULL AND unit_number IS NOT NULL");
  // "Mark as done" on an appointment records who confirmed the meeting happened.
  await query("ALTER TABLE appointments ADD COLUMN IF NOT EXISTS completed_by INTEGER REFERENCES users(id) ON DELETE SET NULL");
  await query("ALTER TABLE appointments ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ");
  // Load: indexes on the columns every list, join and permission check uses, so
  // screens stay fast as the office's data grows. IF NOT EXISTS: safe to rerun.
  for (const [name, definition] of [
    ["idx_appointments_client", "appointments (client_id)"],
    ["idx_appointments_org_start", "appointments (organization_id, starts_at)"],
    ["idx_appointments_status", "appointments (status)"],
    ["idx_audit_logs_org_created", "audit_logs (organization_id, created_at DESC)"],
    ["idx_audit_logs_user", "audit_logs (user_id)"],
    ["idx_contracts_client", "contracts (client_id)"],
    ["idx_contracts_org_created", "contracts (organization_id, created_at DESC)"],
    ["idx_documents_contract", "documents (contract_id)"],
    ["idx_documents_client", "documents (client_id)"],
    ["idx_payments_debt", "payments (debt_id)"],
    ["idx_reminders_debt", "reminders (debt_id)"],
    ["idx_leads_org_created", "leads (organization_id, created_at DESC)"],
    ["idx_leads_task", "leads (task_id)"],
    ["idx_leads_appointment", "leads (appointment_id)"],
    ["idx_leads_client", "leads (client_id)"],
    ["idx_follow_ups_lead", "follow_ups (lead_id)"],
    ["idx_follow_ups_client", "follow_ups (client_id)"],
    ["idx_property_images_property", "property_images (property_id)"],
    ["idx_property_history_property", "property_history (property_id)"],
    ["idx_record_shares_entity_record", "record_shares (entity, record_id)"],
    ["idx_tasks_status", "tasks (status)"],
    ["idx_tasks_department", "tasks (department_id)"],
    ["idx_user_roles_role", "user_roles (role_id)"],
    ["idx_user_departments_department", "user_departments (department_id)"],
    ["idx_role_permissions_permission", "role_permissions (permission_id)"],
    ["idx_duty_permissions_permission", "duty_permissions (permission_id)"],
    ["idx_users_org", "users (organization_id)"],
  ]) await query(`CREATE INDEX IF NOT EXISTS ${name} ON ${definition}`);
  // The morning appointment reminder pops up once per person per day.
  await query("CREATE TABLE IF NOT EXISTS appointment_reminder_days (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, shown_on DATE NOT NULL, shown_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, shown_on))");
  await migrateSellLeads();
  for (const table of scopedTables) {
    await query(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id) ON DELETE SET NULL`);
    await query(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS created_by INTEGER REFERENCES users(id) ON DELETE SET NULL`);
    await query(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS department_id INTEGER REFERENCES departments(id) ON DELETE SET NULL`);
    await query(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'organization'`);
    await query(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS sector TEXT`);
    // The scope predicate filters on all of these, so each gets an index.
    await query(`CREATE INDEX IF NOT EXISTS idx_${table}_owner ON ${table}(owner_id)`);
    await query(`CREATE INDEX IF NOT EXISTS idx_${table}_creator ON ${table}(created_by)`);
    await query(`CREATE INDEX IF NOT EXISTS idx_${table}_department ON ${table}(department_id)`);
  }
  // Listing endpoints order by creation and filter by status.
  await query("CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at)");
  await query("CREATE INDEX IF NOT EXISTS idx_projects_created ON projects(created_at DESC)");
  await query("CREATE INDEX IF NOT EXISTS idx_clients_status ON clients(status)");
  await query("CREATE INDEX IF NOT EXISTS idx_contracts_status ON contracts(status)");
  await query("CREATE INDEX IF NOT EXISTS idx_debts_status ON debts(status)");
  await query("CREATE INDEX IF NOT EXISTS idx_properties_status ON properties(status)");
  await query("CREATE INDEX IF NOT EXISTS idx_appointments_starts ON appointments(starts_at)");
  await query("CREATE INDEX IF NOT EXISTS idx_documents_status ON documents(status)");
  await query("CREATE INDEX IF NOT EXISTS idx_payments_paid ON payments(paid_at DESC)");
  await query("CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status)");
  // List endpoints order by creation/due date and now support offset pagination.
  // The trailing `id` makes the sort key unique, so the planner can satisfy both
  // the ORDER BY and the LIMIT without a sort, and a row cannot move between
  // pages when timestamps collide. Additive only: no existing index is replaced.
  await query("CREATE INDEX IF NOT EXISTS idx_clients_created ON clients(created_at DESC, id DESC)");
  await query("CREATE INDEX IF NOT EXISTS idx_properties_created ON properties(created_at DESC, id DESC)");
  await query("CREATE INDEX IF NOT EXISTS idx_contracts_created ON contracts(created_at DESC, id DESC)");
  // Debts sort by due_date first, then creation - the exact composite ORDER BY.
  await query("CREATE INDEX IF NOT EXISTS idx_debts_due ON debts(due_date ASC, created_at DESC, id DESC)");
  await query("CREATE INDEX IF NOT EXISTS idx_payments_paid_id ON payments(paid_at DESC, id DESC)");
  await query("CREATE INDEX IF NOT EXISTS idx_documents_created ON documents(created_at DESC, id DESC)");
  await query("CREATE INDEX IF NOT EXISTS idx_appointments_starts_id ON appointments(starts_at ASC, id DESC)");
  // Expired sessions would otherwise accumulate forever.
  await query("DELETE FROM sessions WHERE expires_at <= NOW()");
  await withTransaction(async (client) => {
    const org = await client.query("INSERT INTO organizations (name, slug) VALUES ($1, $2) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name RETURNING id", ["MKUYU", "mkuyu"]);
    const organizationId = org.rows[0].id;
    for (const [key, label] of permissions) await client.query("INSERT INTO permissions (permission_key, label) VALUES ($1, $2) ON CONFLICT (permission_key) DO UPDATE SET label = EXCLUDED.label", [key, label]);

    // Align the organization with the MKUYU structure. Departments and roles are
    // renamed in place so every user_departments / user_roles row and every
    // record's department_id survives the upgrade. Where two old departments
    // merge into one, members are moved to the surviving department and the
    // empty shell is removed.
    for (const [oldName, newName] of Object.entries(departmentRenames)) {
      if (oldName === newName) continue;
      const source = (await client.query("SELECT id FROM departments WHERE organization_id=$1 AND name=$2", [organizationId, oldName])).rows[0];
      if (!source) continue;
      let target = (await client.query("SELECT id FROM departments WHERE organization_id=$1 AND name=$2", [organizationId, newName])).rows[0];
      if (!target) {
        // Free the unique (organization_id, name) slot before taking it.
        await client.query("UPDATE departments SET name=$3 WHERE id=$1 AND organization_id=$2", [source.id, organizationId, `${newName} (merging)`]);
        target = (await client.query("UPDATE departments SET name=$3 WHERE id=$1 AND organization_id=$2 RETURNING id", [source.id, organizationId, newName])).rows[0];
      } else {
        await client.query("INSERT INTO user_departments (user_id, department_id) SELECT user_id, $1 FROM user_departments WHERE department_id=$2 ON CONFLICT DO NOTHING", [target.id, source.id]);
        await client.query("UPDATE clients SET department_id=$1 WHERE department_id=$2", [target.id, source.id]);
        await client.query("UPDATE contracts SET department_id=$1 WHERE department_id=$2", [target.id, source.id]);
        await client.query("UPDATE projects SET department_id=$1 WHERE department_id=$2", [target.id, source.id]);
        await client.query("UPDATE properties SET department_id=$1 WHERE department_id=$2", [target.id, source.id]);
        await client.query("DELETE FROM departments WHERE id=$1", [source.id]);
      }
    }
    for (const [oldName, newName] of Object.entries(roleRenames)) {
      const source = (await client.query("SELECT id FROM roles WHERE organization_id=$1 AND name=$2", [organizationId, oldName])).rows[0];
      if (!source) continue;
      const target = (await client.query("SELECT id FROM roles WHERE organization_id=$1 AND name=$2", [organizationId, newName])).rows[0];
      if (target) {
        await client.query("INSERT INTO user_roles (user_id, role_id) SELECT user_id, $1 FROM user_roles WHERE role_id=$2 ON CONFLICT DO NOTHING", [target.id, source.id]);
        await client.query("DELETE FROM roles WHERE id=$1", [source.id]);
      } else {
        await client.query("UPDATE roles SET name=$3 WHERE id=$1 AND organization_id=$2", [source.id, organizationId, newName]);
      }
    }
    // Retire placeholder roles: anyone holding one is moved onto the role that
    // now covers that work, so nobody is left without a role.
    for (const [oldName, newName] of Object.entries(ROLE_REPLACEMENTS)) {
      const source = (await client.query("SELECT id FROM roles WHERE organization_id=$1 AND name=$2", [organizationId, oldName])).rows[0];
      if (!source) continue;
      const target = (await client.query("SELECT id FROM roles WHERE organization_id=$1 AND name=$2", [organizationId, newName])).rows[0];
      if (target) await client.query("INSERT INTO user_roles (user_id, role_id) SELECT user_id, $1 FROM user_roles WHERE role_id=$2 ON CONFLICT DO NOTHING", [target.id, source.id]);
      await client.query("DELETE FROM roles WHERE id=$1", [source.id]);
    }
    for (const name of departments) await client.query("INSERT INTO departments (organization_id, name) VALUES ($1, $2) ON CONFLICT (organization_id, name) DO NOTHING", [organizationId, name]);

    for (const [name, description, rank, scope, keys] of defaultRoles) {
      const inserted = await client.query("INSERT INTO roles (organization_id,name,description,system_role,rank,scope) VALUES($1,$2,$3,TRUE,$4,$5) ON CONFLICT (organization_id,name) DO UPDATE SET active = TRUE, rank = EXCLUDED.rank, description = EXCLUDED.description, scope = EXCLUDED.scope RETURNING id", [organizationId, name, description, rank, scope]);
      const roleId = inserted.rows[0].id;
      await client.query("DELETE FROM role_permissions WHERE role_id=$1", [roleId]);
      for (const key of keys) await client.query("INSERT INTO role_permissions(role_id,permission_id) SELECT $1,id FROM permissions WHERE permission_key=$2 ON CONFLICT DO NOTHING", [roleId, key]);

      // Seed the declared responsibilities for this role. Duties are rewritten
      // wholesale so the catalogue in org/duties.js stays the single source.
      await client.query("DELETE FROM duties WHERE role_id=$1", [roleId]);
      const duties = ROLE_DUTIES[name] || [];
      for (let index = 0; index < duties.length; index += 1) {
        const duty = duties[index];
        const created = await client.query(
          "INSERT INTO duties (organization_id,role_id,duty_key,label,description,sort_order) VALUES($1,$2,$3,$4,$5,$6) RETURNING id",
          [organizationId, roleId, duty.key, duty.label, duty.description || null, index],
        );
        for (const key of duty.permissions) {
          await client.query("INSERT INTO duty_permissions(duty_id,permission_id) SELECT $1,id FROM permissions WHERE permission_key=$2 ON CONFLICT DO NOTHING", [created.rows[0].id, key]);
        }
      }
    }
    // Legacy backfill: roles created before module access existed can still "view"
    // records but hold no `access_*` key at all. Give those roles every business
    // module once so an upgrade never silently locks real staff out; once a role
    // has been given module access by hand this no longer applies.
    await client.query(
      `INSERT INTO role_permissions (role_id, permission_id)
       SELECT rp.role_id, p.id
         FROM (SELECT DISTINCT role_id FROM role_permissions) rp
         CROSS JOIN permissions p
        WHERE p.permission_key LIKE 'access\\_%'
          AND NOT EXISTS (SELECT 1 FROM role_permissions x WHERE x.role_id = rp.role_id AND x.permission_id = p.id)
          AND EXISTS (SELECT 1 FROM role_permissions v JOIN permissions vp ON vp.id = v.permission_id WHERE v.role_id = rp.role_id AND vp.permission_key = 'view')
          AND NOT EXISTS (SELECT 1 FROM roles r WHERE r.id = rp.role_id AND r.name = ANY($1::text[]))
       ON CONFLICT DO NOTHING`,
      [defaultRoles.map(([name]) => name)],
    );
  });
  if (seedDemo) {
    await seedDemoAccounts();
    await rotateLegacyPasswords();
  }
  await repairRetiredRoleDisplayNames();
  // Contact-page messages belong to Customer Service. Messages that arrived
  // before this rule get the same home, once (never an allocated record).
  await query(
    `UPDATE leads l SET department_id = d.id, visibility = 'department'
       FROM departments d
      WHERE d.organization_id = l.organization_id AND d.name = 'CUSTOMER SERVICE'
        AND l.source = 'website-contact' AND l.department_id IS NULL AND l.owner_id IS NULL`,
  );
  // Contact messages handed to Customer Service before hand-offs were linked
  // to them: the task names its message ("(Lead W-7)"), so the link - and with
  // it Customer Service's report - is restored. Only unlinked messages, once.
  await query(
    `UPDATE leads l SET task_id = t.id, handed_off_at = COALESCE(l.handed_off_at, t.created_at), status = CASE WHEN l.status = 'new' THEN 'handed_off' ELSE l.status END
       FROM tasks t
      WHERE l.source = 'website-contact' AND l.task_id IS NULL AND t.organization_id = l.organization_id
        AND t.status <> 'cancelled' AND t.description LIKE '%(Lead W-' || l.id || ')%'
        AND t.id = (SELECT MAX(x.id) FROM tasks x WHERE x.organization_id = l.organization_id AND x.status <> 'cancelled' AND x.description LIKE '%(Lead W-' || l.id || ')%')`,
  );
  // Staff profile photos, and a lawyer's signature image used on contracts.
  for (const column of ["photo_stored_name TEXT", "photo_mime TEXT", "signature_stored_name TEXT", "signature_mime TEXT", "signature_title TEXT"]) {
    await query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS ${column}`);
  }
  // Photos uploaded through the earlier profile_photo_* columns move to the
  // shared photo column (same folder on disk), so nobody loses their picture.
  await query(`UPDATE users SET photo_stored_name = profile_photo_stored_name, photo_mime = profile_photo_mime_type
                WHERE photo_stored_name IS NULL AND profile_photo_stored_name IS NOT NULL`);
  // Which lawyer's signature is on a contract, and when it was applied.
  await query("ALTER TABLE contracts ADD COLUMN IF NOT EXISTS legal_signed_by INTEGER REFERENCES users(id) ON DELETE SET NULL");
  await query("ALTER TABLE contracts ADD COLUMN IF NOT EXISTS legal_signed_at TIMESTAMPTZ");
  // One contract template may be the organization's default.
  await query("ALTER TABLE documents ADD COLUMN IF NOT EXISTS is_default_template BOOLEAN NOT NULL DEFAULT FALSE");
  // The placeholder values a contract was generated with, when it was produced
  // on an uploaded Word template, so the same file can be re-filled at signing.
  await query("ALTER TABLE documents ADD COLUMN IF NOT EXISTS fill_values JSONB");
  // Contracts already past Sales get the hand-over shares they were missing.
  await backfillHandoverShares();
  // Customer notices by SMS / e-mail (notify/customerNotices.js). One row per
  // notice; the partial unique index is what guarantees a notice is sent once
  // (a failed one frees its key so the next run retries it).
  await query(`CREATE TABLE IF NOT EXISTS notification_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL, channel TEXT NOT NULL CHECK (channel IN ('sms','email')),
    dedupe_key TEXT NOT NULL, recipient TEXT, message TEXT,
    status TEXT NOT NULL CHECK (status IN ('sending','sent','test','failed','off')),
    error TEXT, provider TEXT, provider_ref TEXT,
    contract_id INTEGER REFERENCES contracts(id) ON DELETE SET NULL,
    debt_id INTEGER REFERENCES debts(id) ON DELETE SET NULL,
    payment_id INTEGER REFERENCES payments(id) ON DELETE SET NULL,
    property_id INTEGER REFERENCES properties(id) ON DELETE SET NULL,
    client_id INTEGER REFERENCES clients(id) ON DELETE SET NULL,
    lead_id INTEGER REFERENCES leads(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), sent_at TIMESTAMPTZ)`);
  await query("CREATE UNIQUE INDEX IF NOT EXISTS notification_log_once ON notification_log (channel, dedupe_key) WHERE status IN ('sending','sent','test')");
  await query("CREATE INDEX IF NOT EXISTS notification_log_created ON notification_log (created_at DESC)");
  // Offers about new properties go only to people who agreed to receive them.
  for (const table of ["clients", "leads"]) {
    await query(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS marketing_opt_in BOOLEAN NOT NULL DEFAULT FALSE`);
    await query(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS marketing_opt_in_at TIMESTAMPTZ`);
  }
  await migrateCustomerPortal();
}

/**
 * The diaspora customer portal (routes/customer.js). Only a client marked
 * diaspora, and invited by Sales, can sign in; they sign in with a one-time
 * code sent to their e-mail (no password). Customer accounts, codes and
 * sessions are separate from staff users and sessions on purpose.
 */
async function migrateCustomerPortal() {
  await query("ALTER TABLE clients ADD COLUMN IF NOT EXISTS is_diaspora BOOLEAN NOT NULL DEFAULT FALSE");
  await query("ALTER TABLE clients ADD COLUMN IF NOT EXISTS country TEXT");
  // Self sign-up (diaspora): where they live decides the desk, nationality
  // decides what Legal may offer, the phone's country is a cross-check.
  for (const column of [
    "nationality TEXT", "residence_code TEXT", "phone_country TEXT", "residence_check TEXT",
    // NULL = added by staff (trusted). Self sign-ups move: unverified -> submitted
    // (documents uploaded) -> verified (by the Diaspora Desk), or rejected; Legal
    // then confirms nationality (citizenship_confirmed_at). desk_checked is legacy.
    "verification_status TEXT", "verification_note TEXT",
    "desk_checked_by INTEGER REFERENCES users(id) ON DELETE SET NULL", "desk_checked_at TIMESTAMPTZ",
    "verified_by INTEGER REFERENCES users(id) ON DELETE SET NULL", "verified_at TIMESTAMPTZ",
    // The desk member who knows this customer best. The desk works as one shared
    // queue, so this is a contact person, never a lock.
    "diaspora_officer_id INTEGER REFERENCES users(id) ON DELETE SET NULL",
  ]) await query(`ALTER TABLE clients ADD COLUMN IF NOT EXISTS ${column}`);
  // The Diaspora Desk verifies identity (the customer may then request
  // properties); Legal confirms nationality afterwards, before any agreement is
  // signed. Customers verified before this split were verified by Legal, so
  // their nationality is already confirmed: copied over once, when the column
  // first appears.
  const hadCitizenship = await queryOne("SELECT 1 FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='clients' AND column_name='citizenship_confirmed_at'");
  await query("ALTER TABLE clients ADD COLUMN IF NOT EXISTS citizenship_confirmed_by INTEGER REFERENCES users(id) ON DELETE SET NULL");
  await query("ALTER TABLE clients ADD COLUMN IF NOT EXISTS citizenship_confirmed_at TIMESTAMPTZ");
  await query("ALTER TABLE documents ADD COLUMN IF NOT EXISTS expires_on DATE");
  if (!hadCitizenship) {
    await query("UPDATE clients SET citizenship_confirmed_at=verified_at, citizenship_confirmed_by=verified_by WHERE verification_status='verified' AND citizenship_confirmed_at IS NULL");
  }
  await query(`CREATE TABLE IF NOT EXISTS customer_signups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL, details JSONB NOT NULL, password_hash TEXT NOT NULL,
    code_hash TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0, used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await query(`CREATE TABLE IF NOT EXISTS customer_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL UNIQUE REFERENCES clients(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'invited' CHECK (status IN ('invited','active','disabled')),
    invited_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    invited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    activated_at TIMESTAMPTZ, last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await query("ALTER TABLE customer_accounts ADD COLUMN IF NOT EXISTS password_hash TEXT");
  // Sign in with a username or the e-mail, plus the password. The e-mailed code
  // is used only to sign up and to reset a forgotten password.
  await query("ALTER TABLE customer_accounts ADD COLUMN IF NOT EXISTS username TEXT");
  // Diaspora contracts: their own wording and path, and the customer's
  // electronic signature in the portal (who, when, from where, which text).
  for (const column of ["channel TEXT NOT NULL DEFAULT 'standard'", "customer_accepted_at TIMESTAMPTZ", "customer_accepted_name TEXT",
    "customer_accepted_ip TEXT", "customer_accepted_agent TEXT", "customer_accepted_hash TEXT", "customer_accepted_text TEXT"]) {
    await query(`ALTER TABLE contracts ADD COLUMN IF NOT EXISTS ${column}`);
  }
  await query("CREATE UNIQUE INDEX IF NOT EXISTS customer_accounts_username ON customer_accounts (lower(username)) WHERE username IS NOT NULL");
  // One live account per e-mail address, so a code can never reach two clients.
  await query("CREATE UNIQUE INDEX IF NOT EXISTS customer_accounts_email ON customer_accounts (lower(email)) WHERE status <> 'disabled'");
  await query(`CREATE TABLE IF NOT EXISTS customer_login_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES customer_accounts(id) ON DELETE CASCADE,
    code_hash TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0, used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await query("CREATE INDEX IF NOT EXISTS customer_login_codes_account ON customer_login_codes (account_id, created_at DESC)");
  await query(`CREATE TABLE IF NOT EXISTS customer_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash TEXT NOT NULL UNIQUE,
    account_id INTEGER NOT NULL REFERENCES customer_accounts(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_seen_at TIMESTAMPTZ)`);
  // Construction progress that staff publish for the customers of a project
  // (or of one property in it): a dated note with photos.
  await query(`CREATE TABLE IF NOT EXISTS construction_updates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    property_id INTEGER REFERENCES properties(id) ON DELETE SET NULL,
    title TEXT NOT NULL, note TEXT,
    update_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await query("CREATE INDEX IF NOT EXISTS construction_updates_project ON construction_updates (project_id, update_date DESC)");
  await query(`CREATE TABLE IF NOT EXISTS construction_update_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_id INTEGER NOT NULL REFERENCES construction_updates(id) ON DELETE CASCADE,
    stored_name TEXT NOT NULL, original_filename TEXT, mime_type TEXT, file_size BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
}

/**
 * Demo accounts, one per department, so the organization can be demonstrated
 * end to end.
 *
 * They are ordinary staff accounts created through the same tables and the same
 * `hashPassword` used by the real sign-up path; nothing here bypasses the
 * authorization model or grants a role extra permissions. The email domain
 * (`.demo.mkuyu.local`) keeps them unmistakably separate from a real staff
 * account, and `MkuDemo#<role>` marks the credentials as non-production.
 *
 * Idempotent: an existing account has its role, department and password reset to
 * the values below, so running this rotates the demo passwords (Task 3).
 */
const demoAccounts = [
  { email: "md@demo.mkuyu.local", display_name: "Joseph Mwakalinga", role: "Managing Director", department: "MANAGEMENT" },
  { email: "finance.manager@demo.mkuyu.local", display_name: "Grace Mushi", role: "Finance Manager", department: "FINANCE & ACCOUNTS" },
  { email: "finance@demo.mkuyu.local", display_name: "Peter Ndosi", role: "Finance Officer", department: "FINANCE & ACCOUNTS" },
  { email: "sales.manager@demo.mkuyu.local", display_name: "Daniel Kibe", role: "Department Manager", department: "SALES, MARKETING & OPERATIONS" },
  { email: "sales@demo.mkuyu.local", display_name: "Amina Sanga", role: "Sales, Marketing & Operations Officer", department: "SALES, MARKETING & OPERATIONS" },
  { email: "legal.manager@demo.mkuyu.local", display_name: "Fatuma Juma", role: "Legal Manager", department: "LEGAL" },
  { email: "legal@demo.mkuyu.local", display_name: "Baraka Said", role: "Legal Officer", department: "LEGAL" },
  { email: "icto@demo.mkuyu.local", display_name: "Neema Ally", role: "ICTO", department: "ICT & ADMINISTRATION" },
  { email: "itsupport@demo.mkuyu.local", display_name: "Salim Mwakalinga", role: "Administration & IT Support Officer", department: "ICT & ADMINISTRATION" },
  { email: "cs.manager@demo.mkuyu.local", display_name: "Zainab Mbeki", role: "Customer Service Manager", department: "CUSTOMER SERVICE" },
  { email: "cs@demo.mkuyu.local", display_name: "Asha Rajabu", role: "Customer Service Officer", department: "CUSTOMER SERVICE" },
  { email: "diaspora.manager@demo.mkuyu.local", display_name: "Rehema Kweka", role: "Diaspora Desk Manager", department: "DIASPORA DESK" },
  { email: "diaspora@demo.mkuyu.local", display_name: "Musa Chande", role: "Diaspora Desk Officer", department: "DIASPORA DESK" },
];

/** Deterministic per-account password. Defined in org/demoCredentials.js. */
export { demoPasswordFor };

/**
 * Repair leftover display names from retired roles.
 *
 * A demo user was once created with the display name "Sales and Marketing
 * Officer", which is the name of a role that no longer exists. Only the display
 * name is rewritten: the user row, its id, and every record it owns are left
 * untouched, so no membership or business data is lost. A person is never
 * renamed to a role they do not hold.
 */
async function repairRetiredRoleDisplayNames() {
  const retired = Object.keys(ROLE_REPLACEMENTS);
  if (!retired.length) return;
  const org = await organizationId();
  const users = await query(
    `SELECT u.id,u.display_name,u.email,
            COALESCE((SELECT r.name FROM user_roles ur JOIN roles r ON r.id=ur.role_id
                       WHERE ur.user_id=u.id ORDER BY r.rank DESC LIMIT 1),'') AS current_role
       FROM users u WHERE u.organization_id=$1 AND u.display_name=ANY($2::text[])`,
    [org, retired],
  );
  for (const user of users.rows) {
    if (user.current_role === user.display_name) {
      // The name was still accurate: keep it, the role exists under it.
      continue;
    }
    const replacement = user.current_role || "MKUYU Staff";
    // `<role> · <email local part>` stays unique and traceable to the original.
    const newName = `${replacement} (${String(user.email).split("@")[0]})`.slice(0, 80);
    await query("UPDATE users SET display_name=$1 WHERE id=$2", [newName, user.id]);
    console.log(`renamed stale display name "${user.display_name}" -> "${newName}" (user ${user.id}, role "${user.current_role}")`);
  }
}

/**
 * Rotate the passwords of the legacy accounts that predate the demo set.
 *
 * Deliberately narrow: this touches `password_hash` and nothing else. The user
 * id, email, display name, `role` column, user_roles, user_departments and every
 * owned record stay exactly as they were. Sessions are dropped so a token issued
 * against the old credential cannot outlive the rotation.
 *
 * Records an audit event per rotation so the change is traceable.
 */
async function rotateLegacyPasswords() {
  const org = await organizationId();
  for (const account of LEGACY_ACCOUNTS) {
    const user = await queryOne("SELECT id,email,password_hash FROM users WHERE email=$1 AND organization_id=$2", [account.email, org]);
    if (!user) continue;
    const target = legacyPasswordFor(account.email);
    // Idempotent in two independent parts, so a server restart never churns
    // hashes or drops live sessions, and a rotation that happened before its
    // audit event was recorded still gets the event.
    if (!verifyPassword(target, user.password_hash)) {
      await query("UPDATE users SET password_hash=$1 WHERE id=$2", [hashPassword(target), user.id]);
      await query("DELETE FROM sessions WHERE user_id=$1", [user.id]);
      console.log(`rotated the password for ${account.email} (user ${user.id}); preserved id, role, department and history`);
    }
    const audited = await queryOne(
      "SELECT 1 FROM audit_logs WHERE user_id=$1 AND action='password_rotated' LIMIT 1", [user.id],
    );
    if (!audited) {
      await query(
        `INSERT INTO audit_logs (organization_id,user_id,action,module,record_id,details_json)
         VALUES ($1,$2,'password_rotated','user',$3,$4::jsonb)`,
        [org, user.id, String(user.id), JSON.stringify({ email: account.email, reason: "legacy demo credential rotation", sessions_invalidated: true })],
      );
    }
  }
}

async function seedDemoAccounts() {
  const org = await organizationId();
  for (const account of demoAccounts) {
    const role = await queryOne("SELECT id FROM roles WHERE organization_id=$1 AND name=$2", [org, account.role]);
    const department = await queryOne("SELECT id FROM departments WHERE organization_id=$1 AND name=$2", [org, account.department]);
    if (!role || !department) {
      console.warn(`demo seed skipped ${account.email}: role or department missing`);
      continue;
    }
    const password = demoPasswordFor(account.email);
    const existing = await queryOne("SELECT id FROM users WHERE email=$1", [account.email]);
    let userId;
    if (existing) {
      // Reset the demo password and repair the display name from a retired role.
      await query("UPDATE users SET display_name=$1, password_hash=$2, active=TRUE WHERE id=$3", [account.display_name, hashPassword(password), existing.id]);
      userId = existing.id;
    } else {
      const created = await queryOne(
        "INSERT INTO users (organization_id, email, password_hash, display_name, role) VALUES ($1,$2,$3,$4,'staff') RETURNING id",
        [org, account.email, hashPassword(password), account.display_name],
      );
      userId = created.id;
    }
    // Exactly one role and one department, so a demo account can never drift
    // outside the permissions its role defines.
    await withTransaction(async (client) => {
      await client.query("DELETE FROM user_roles WHERE user_id=$1", [userId]);
      await client.query("INSERT INTO user_roles (user_id, role_id) VALUES ($1,$2)", [userId, role.id]);
      await client.query("DELETE FROM user_departments WHERE user_id=$1", [userId]);
      await client.query("INSERT INTO user_departments (user_id, department_id) VALUES ($1,$2)", [userId, department.id]);
    });
  }
}

if (process.argv.includes("--seed-only")) {
  if (String(process.env.NODE_ENV || "").toLowerCase() === "production") {
    throw new Error("demo seeding is disabled in production");
  }
  // Seeding resets every demo and legacy account (admin included) to the
  // published MkuDemo# passwords. On the real database that would undo every
  // password change, so it needs an explicit opt-in there.
  if (process.env.MKUYU_IS_TEST_DATABASE !== "1" && process.env.MKUYU_ALLOW_DEMO_RESEED !== "1") {
    throw new Error("npm run seed would reset every account's password to the demo scheme on this database. If you really want that, set MKUYU_ALLOW_DEMO_RESEED=1 and run it again.");
  }
  await runMigrations({ seedDemo: true });
  console.log("PostgreSQL schema ready");
}
