// Downloads the two typefaces the interface uses (Manrope, Cormorant Garamond)
// into frontend/fonts, so the system looks the same without internet access.
// Run once on a computer with internet:  node tools/fetch_fonts.mjs
// (or double-click fetch-fonts.bat). The files are then served by MKUYU itself.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const target = path.join(root, "frontend", "fonts");
const cssUrl = "https://fonts.googleapis.com/css2?family=Manrope:wght@400..800&family=Cormorant+Garamond:wght@500..700&display=swap";
// A current browser's user agent makes Google answer with woff2 files.
const userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

const response = await fetch(cssUrl, { headers: { "User-Agent": userAgent } });
if (!response.ok) { console.error(`Could not reach Google Fonts (${response.status}). Check the internet connection and try again.`); process.exit(1); }
let css = await response.text();
fs.mkdirSync(target, { recursive: true });
const blocks = css.split("@font-face").slice(1);
let kept = "/* Generated by tools/fetch_fonts.mjs: the interface fonts, served locally. */\n";
let count = 0;
for (const block of blocks) {
  const subset = (css.slice(0, css.indexOf(block)).match(/\/\*\s*([\w-]+)\s*\*\/\s*$/) || [])[1] || "";
  if (subset && !["latin", "latin-ext"].includes(subset)) continue; // Swahili and English need only these
  const url = (block.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
  const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || "font";
  if (!url) continue;
  const name = `${family.toLowerCase().replace(/\s+/g, "-")}-${subset || "all"}.woff2`;
  const file = await fetch(url, { headers: { "User-Agent": userAgent } });
  if (!file.ok) { console.error(`Download failed: ${url}`); process.exit(1); }
  fs.writeFileSync(path.join(target, name), Buffer.from(await file.arrayBuffer()));
  kept += `/* ${subset} */\n@font-face${block.replace(url, `/fonts/${name}`)}`;
  count += 1;
}
fs.writeFileSync(path.join(target, "fonts.css"), kept);
console.log(`Saved ${count} font files to frontend/fonts. MKUYU now serves its own fonts.`);
